using GigaClaw.Core.Tests.Helpers;

namespace GigaClaw.Core.Tests.Automation;

/// <summary>
/// Guards <c>ai_citation_score.py</c> against the deadlock it once caused: agents stopped emitting
/// inline <c>&lt;script type="application/ld+json"&gt;</c> blocks (schema is now generated by the
/// site template from frontmatter into the document <c>&lt;head&gt;</c>), but the score's
/// structured-data component still hardcoded 20 points to that literal tag. Every post capped at
/// 80/100, permanently below blog-seo's 85-point GEO gate (blog-seo/SKILL.md), which burned both
/// writer/reviewer retry cycles and deadlocked every ticket on <c>owner</c> in <c>Blocked</c>.
///
/// <para>The fix reframed those 20 points to measure whether frontmatter carries what the site
/// template needs to generate BlogPosting/FAQPage/HowTo schema, instead of looking for inline
/// JSON-LD. The Python self-test is the actual regression check (it builds representative posts
/// with zero inline JSON-LD and asserts the max-achievable score is still 100 and clears 85); this
/// test just wires that self-test idiom into `dotnet test`, matching every sibling contract script
/// (verdict_contract.py, handoff_contract.py).</para>
/// </summary>
public class TemplateAiCitationScoreTests
{
    [Fact]
    public void Self_test_passes()
    {
        var (exitCode, output) = PythonContractRunner.RunScript("ai_citation_score.py", "--self-test");
        Assert.True(exitCode == 0, $"ai_citation_score.py --self-test failed:{Environment.NewLine}{output}");
    }

    [Fact]
    public void A_fully_valid_post_with_no_inline_json_ld_clears_the_blog_seo_85_point_gate()
    {
        // Independent of the Python self-test: exercises the script the way blog-writer and
        // blog-seo actually invoke it (a real file on disk, human-readable report on stdout), on a
        // post shaped exactly like what agents produce today — frontmatter-only structured data,
        // never an inline <script type="application/ld+json"> block.
        var workspace = Directory.CreateTempSubdirectory("giga-citation-score-test");
        try
        {
            var path = Path.Combine(workspace.FullName, "post.md");
            File.WriteAllText(path, RepresentativePost);

            var (exitCode, output) = PythonContractRunner.RunScript("ai_citation_score.py", path);

            Assert.True(exitCode == 0, $"ai_citation_score.py failed on a representative post:{Environment.NewLine}{output}");
            Assert.DoesNotContain("<script type=\"application/ld+json\">", RepresentativePost, StringComparison.Ordinal);

            var scoreLine = output
                .Split(Environment.NewLine)
                .FirstOrDefault(line => line.Contains("Overall GEO Score", StringComparison.Ordinal));
            Assert.False(string.IsNullOrEmpty(scoreLine), $"no score line in output:{Environment.NewLine}{output}");

            var score = int.Parse(scoreLine!.Split(':')[1].Trim().Split('/')[0].Trim());
            Assert.True(score >= 85, $"representative post scored {score}/100, below blog-seo's 85-point gate:{Environment.NewLine}{output}");
        }
        finally
        {
            workspace.Delete(recursive: true);
        }
    }

    private const string RepresentativePost = """
        ---
        title: "A Complete Guide to Widget Automation"
        description: "Everything you need to know about automating widgets, from setup to advanced tuning techniques for busy teams."
        date: "2026-07-27"
        author: "A. Writer"
        tags: [automation, widgets]
        canonical: "https://docs.test/blog/widget-automation"
        og_title: "A Complete Guide to Widget Automation"
        og_description: "Everything you need to know about automating widgets, from setup to advanced tuning techniques for busy teams."
        og_image: "/images/widget-automation.png"
        faq:
          - question: "What is widget automation?"
            answer: "Widget automation is the practice of scripting repetitive widget configuration tasks."
          - question: "Why does it matter?"
            answer: "It reduces manual errors and frees engineering time for higher-value work."
        howto_steps:
          - name: "Install the CLI"
            text: "Run the installer and confirm the widget-cli binary is on PATH."
          - name: "Configure the manifest"
            text: "Create a widgets.yaml file describing each automated widget."
        ---
        # How to Automate Widgets: A Best-Practice Guide

        ## Key Takeaways

        Widget automation is a repeatable process that removes manual toil.

        ## What Is Widget Automation?

        Widget automation refers to the use of scripts and templates to configure widgets without manual steps. See the [official widget docs](https://docs-example.test/widgets) for background.

        ## Comparison: Manual vs Automated

        | Approach | Setup Time | Error Rate |
        | --- | --- | --- |
        | Manual | Slow | High |
        | Automated | Fast | Low |

        ## Steps

        1. Install the CLI.
        2. Configure the manifest.
        3. Run the automation job.

        ```bash
        widget-cli run --config widgets.yaml
        ```

        ## Frequently Asked Questions

        ### What is widget automation?

        Widget automation is the practice of scripting repetitive widget configuration tasks.

        ### Why does it matter?

        It reduces manual errors and frees engineering time for higher-value work.
        """;
}
