using System.Text;
using System.Text.Json;
using GigaClaw.Core.Services;

namespace GigaClaw.Catalog;

public sealed record AgentCatalogEntry(
    string Slug,
    bool ContractPresent,
    bool ModelDefaultPresent,
    bool ResolvedModelPresent,
    IReadOnlyList<string> Teams,
    IReadOnlyList<string> DispatchingAutomations,
    bool EvalBaselinePresent);

public sealed record CatalogSummary(int Agents, int Automations, int EnabledAutomations, int ModelDefaults);

public sealed record SystemCatalog(int Version, CatalogSummary Summary, IReadOnlyList<AgentCatalogEntry> Agents);

public sealed class CatalogGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };

    public SystemCatalog Generate(string repositoryRoot)
    {
        var agentsDirectory = Path.Combine(repositoryRoot, "ProjectTemplate", "Agents");
        var slugs = Directory.EnumerateFiles(agentsDirectory, "SKILL.md", SearchOption.AllDirectories)
            .Select(Path.GetDirectoryName)
            .Where(path => path is not null)
            .Select(path => Path.GetFileName(path!))
            .OrderBy(slug => slug, StringComparer.Ordinal)
            .ToArray();

        using var contractsDocument = JsonDocument.Parse(File.ReadAllText(Path.Combine(agentsDirectory, "contracts.json")));
        var contractSlugs = contractsDocument.RootElement.GetProperty("agents").EnumerateObject()
            .Select(property => property.Name).ToHashSet(StringComparer.Ordinal);
        using var modelsDocument = JsonDocument.Parse(File.ReadAllText(Path.Combine(agentsDirectory, "models.json")));
        var modelSlugs = modelsDocument.RootElement.EnumerateObject()
            .Where(property => !property.Name.StartsWith('_'))
            .Select(property => property.Name).ToHashSet(StringComparer.Ordinal);
        using var automationsDocument = JsonDocument.Parse(File.ReadAllText(Path.Combine(agentsDirectory, "automations.json")));
        var automations = ReadAutomations(automationsDocument.RootElement);
        var teamsByAgent = new AgentTeamService().GetTeams()
            .Where(team => team.AgentSlugs.Count > 0)
            .SelectMany(team => team.AgentSlugs.Select(slug => (slug, team.Slug)))
            .GroupBy(pair => pair.slug, StringComparer.Ordinal)
            .ToDictionary(group => group.Key, group => (IReadOnlyList<string>)group.Select(pair => pair.Slug).OrderBy(value => value, StringComparer.Ordinal).ToArray(), StringComparer.Ordinal);

        var entries = slugs.Select(slug => new AgentCatalogEntry(
            slug,
            contractSlugs.Contains(slug),
            modelSlugs.Contains(slug),
            automations.Any(automation => automation.Agents.Contains(slug)),
            teamsByAgent.GetValueOrDefault(slug, Array.Empty<string>()),
            automations.Where(automation => automation.Agents.Contains(slug)).Select(automation => automation.Id).OrderBy(id => id, StringComparer.Ordinal).ToArray(),
            EvalBaselinePresent: false)).ToArray();

        return new SystemCatalog(1, new CatalogSummary(entries.Length, automations.Count, automations.Count(automation => automation.Enabled), modelSlugs.Count), entries);
    }

    public void WriteGeneratedFiles(string repositoryRoot, SystemCatalog catalog)
    {
        File.WriteAllText(Path.Combine(repositoryRoot, "catalog.json"), JsonSerializer.Serialize(catalog, JsonOptions) + "\n");
        File.WriteAllText(Path.Combine(repositoryRoot, "doc", "catalog.md"), RenderMarkdown(catalog));
    }

    public static string RenderMarkdown(SystemCatalog catalog)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# System catalog");
        builder.AppendLine();
        builder.AppendLine("Generated by `dotnet run --project GigaClaw.Catalog -- generate`. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine($"- Agents: {catalog.Summary.Agents}");
        builder.AppendLine($"- Automations: {catalog.Summary.Automations} ({catalog.Summary.EnabledAutomations} enabled)");
        builder.AppendLine($"- Explicit model defaults: {catalog.Summary.ModelDefaults}");
        builder.AppendLine();
        builder.AppendLine("| Agent | Contract | Explicit default | Dispatch model | Teams | Dispatching automations | Eval baseline |");
        builder.AppendLine("| --- | --- | --- | --- | --- | --- | --- |");
        foreach (var agent in catalog.Agents)
            builder.AppendLine($"| {agent.Slug} | {YesNo(agent.ContractPresent)} | {YesNo(agent.ModelDefaultPresent)} | {YesNo(agent.ResolvedModelPresent)} | {Join(agent.Teams)} | {Join(agent.DispatchingAutomations)} | {YesNo(agent.EvalBaselinePresent)} |");
        return builder.ToString();
    }

    private static string YesNo(bool value) => value ? "yes" : "no";
    private static string Join(IReadOnlyList<string> values) => values.Count == 0 ? "—" : string.Join(", ", values);

    private static List<AutomationInfo> ReadAutomations(JsonElement root)
    {
        var result = new List<AutomationInfo>();
        foreach (var automation in root.GetProperty("automations").EnumerateArray())
        {
            var agents = new HashSet<string>(StringComparer.Ordinal);
            var assignees = automation.TryGetProperty("conditions", out var conditions)
                ? conditions.EnumerateArray().Where(condition => condition.TryGetProperty("type", out var type) && type.GetString() == "assignedTo")
                    .SelectMany(condition => condition.GetProperty("slugs").EnumerateArray().Select(slug => slug.GetString()!))
                : Enumerable.Empty<string>();
            foreach (var action in automation.GetProperty("actions").EnumerateArray())
            {
                if (!action.TryGetProperty("type", out var type) || type.GetString() != "runAgent") continue;
                var agent = action.GetProperty("agent").GetString();
                if (agent == "{assignee}") agents.UnionWith(assignees);
                else if (!string.IsNullOrWhiteSpace(agent)) agents.Add(agent);
            }
            result.Add(new AutomationInfo(automation.GetProperty("id").GetString()!, automation.GetProperty("enabled").GetBoolean(), agents));
        }
        return result;
    }

    private sealed record AutomationInfo(string Id, bool Enabled, HashSet<string> Agents);
}
