#!/usr/bin/env python3
"""
ai_citation_score.py - Heuristic AI Citation Readiness & GEO (Generative Engine Optimization) score helper.

Evaluates content structure for LLM retrieval and citation:
  - Self-contained definitions
  - Comparison tables
  - Bulleted summary lists
  - Structured-data readiness (frontmatter the site template needs to generate schema)
  - Direct Q&A FAQ headers

Pass --self-test to run the built-in regression check instead of scoring a file.

Structured data is generated by the consuming website's template from CMS
fields into the document <head> — agents do not emit inline
`<script type="application/ld+json">` blocks in markdown bodies. This script
therefore does not look for inline JSON-LD; it scores whether the post's
frontmatter carries what the template needs to generate BlogPosting, FAQPage,
and HowTo schema:
  - title, description (or excerpt), date, author for BlogPosting
  - a `faq:` list of {question, answer} entries, required only when the post
    has an FAQ-style heading
  - a `howto_steps:` list of {name, text} entries, required only when the
    post reads as step-by-step (same heuristic as content_contract.py's
    `looks_like_howto`)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

from content_contract import frontmatter as parse_frontmatter
from content_contract import looks_like_howto


def _raw_frontmatter_block(text: str) -> str:
    """Return the raw text between the `---` frontmatter delimiters, or ''
    if the document has none. Deliberately duplicated as raw text (rather
    than only using the parsed scalar dict from content_contract.frontmatter)
    because the FAQ/HowTo readiness checks below need the indented list
    blocks that a scalar-only parser skips."""
    if not text.startswith("---\n"):
        return ""
    end = text.find("\n---\n", 4)
    if end < 0:
        return ""
    return text[4:end]


def _top_level_block(frontmatter_text: str, key: str) -> str:
    """Return the indented lines following a top-level `key:` entry in a YAML
    frontmatter block, stopping at the next top-level key or end of block.
    Deliberately shallow — presence/shape detection only, not a YAML parser
    (matches the dependency-free approach every sibling script in this
    folder uses; see sync_draft_to_description.py's docstring)."""
    capturing = False
    block: list[str] = []
    for line in frontmatter_text.splitlines():
        if re.match(rf"^{re.escape(key)}:\s*$", line):
            capturing = True
            continue
        if capturing:
            if line.strip() == "" or line[:1].isspace():
                block.append(line)
                continue
            break
    return "\n".join(block)


def _has_paired_entries(block: str, key_a: str, key_b: str) -> bool:
    """True when a YAML list-of-mappings block carries at least one entry
    with both keys — e.g. `- question: ...` / `  answer: ...` — so a lone
    `question:` with no matching `answer:` (or vice versa) does not count as
    structured data the template can actually use."""
    count_a = len(re.findall(rf"^\s*-?\s*{key_a}\s*:", block, re.MULTILINE))
    count_b = len(re.findall(rf"^\s*-?\s*{key_b}\s*:", block, re.MULTILINE))
    return count_a > 0 and count_b > 0 and count_a == count_b


def evaluate_geo_citability(text: str) -> dict[str, Any]:
    score = 0
    breakdown: dict[str, str] = {}

    # 1. Heading Hierarchy & Clarity (20 pts)
    headers = re.findall(r'^#{1,4}\s+(.+)$', text, re.MULTILINE)
    if len(headers) >= 3:
        score += 15
        breakdown['headers'] = "Good header structure (15/20)"
        # Extra points if headers contain query phrases (How, What, Why, Best)
        if any(re.search(r'\b(how|what|why|best|vs|guide)\b', h, re.IGNORECASE) for h in headers):
            score += 5
            breakdown['headers'] += " + Query-matched headings (+5)"
    else:
        breakdown['headers'] = "Weak header hierarchy (0/20)"

    # 2. Extractable Structural Data: Tables & Lists (25 pts)
    # Table = a markdown separator row (handles both `|---|---|` and `| --- | --- |`).
    has_table = bool(re.search(r'^(?=.*\|)\s*\|?[\s:|-]*-{3,}[\s:|-]*\|?\s*$', text, re.MULTILINE))
    # List = dash/star/plus bullets or numbered items.
    has_list = bool(re.search(r'^\s*(?:[-*+]|\d{1,3}\.)\s+', text, re.MULTILINE))

    table_score = 15 if has_table else 0
    list_score = 10 if has_list else 0
    score += (table_score + list_score)
    breakdown['structural_data'] = f"Tables ({table_score}/15), Lists ({list_score}/10)"

    # 3. Structured-Data Readiness (20 pts) — the site template generates
    # BlogPosting/FAQPage/HowTo JSON-LD from frontmatter, so this measures
    # whether the frontmatter carries what the template needs, not whether
    # the body contains a literal <script type="application/ld+json"> tag.
    meta, body, _fm_errors = parse_frontmatter(text)
    frontmatter_text = _raw_frontmatter_block(text)

    title_ok = bool(meta.get('title', '').strip())
    description_ok = bool(meta.get('description', '').strip() or meta.get('excerpt', '').strip())
    date_ok = bool(meta.get('date', '').strip())
    author_ok = bool(meta.get('author', '').strip())
    core_score = 2 * sum([title_ok, description_ok, date_ok, author_ok])

    heading_pairs = [(len(mark), title.strip()) for mark, title in re.findall(r'^(#{1,6})\s+(.+)$', body, re.MULTILINE)]
    has_faq_heading = any(re.search(r'\b(faq|frequently asked)\b', title, re.IGNORECASE) for _, title in heading_pairs)
    is_howto = looks_like_howto(heading_pairs)

    has_faq_data = _has_paired_entries(_top_level_block(frontmatter_text, 'faq'), 'question', 'answer')
    # A post with no FAQ section isn't penalized for lacking FAQ data; one
    # that writes an FAQ in prose without structured data loses the points,
    # because FAQPage JSON-LD cannot be generated from prose alone.
    faq_score = 6 if (not has_faq_heading or has_faq_data) else 0

    has_howto_data = _has_paired_entries(_top_level_block(frontmatter_text, 'howto_steps'), 'name', 'text')
    howto_score = 6 if (not is_howto or has_howto_data) else 0

    schema_score = core_score + faq_score + howto_score
    score += schema_score
    breakdown['schema'] = (
        f"Core BlogPosting fields ({core_score}/8), "
        f"FAQ readiness ({faq_score}/6"
        + ("" if has_faq_heading else ", no FAQ section")
        + f"), HowTo readiness ({howto_score}/6"
        + ("" if is_howto else ", not a how-to")
        + ")"
    )

    # 4. Definition Clarity & TL;DR Box (20 pts)
    has_tldr = bool(re.search(r'\b(tldr|key takeaways|summary|quick overview)\b', text, re.IGNORECASE))
    tldr_score = 10 if has_tldr else 0

    # Check for direct definition patterns ("X is a ...", "X refers to ...")
    has_definition = bool(re.search(r'\b(is a|refers to|defined as|consists of)\b', text, re.IGNORECASE))
    def_score = 10 if has_definition else 0

    score += (tldr_score + def_score)
    breakdown['definition_tldr'] = f"TL;DR Callout ({tldr_score}/10), Direct Definitions ({def_score}/10)"

    # 5. Citations & Code Evidence (15 pts)
    has_links = bool(re.search(r'\[.+\]\(https?://.+\)', text))
    has_code = '```' in text
    link_score = 10 if has_links else 0
    code_score = 5 if has_code else 0
    score += (link_score + code_score)
    breakdown['evidence'] = f"External Links ({link_score}/10), Code Blocks ({code_score}/5)"

    return {
        "score": min(100, score),
        "breakdown": breakdown
    }


_SELF_TEST_BASE = """---
title: "A Complete Guide to Widget Automation"
description: "Everything you need to know about automating widgets, from setup to advanced tuning techniques for busy teams."
date: "2026-07-27"
author: "A. Writer"
tags: [automation, widgets]
canonical: "https://docs.test/blog/widget-automation"
og_title: "A Complete Guide to Widget Automation"
og_description: "Everything you need to know about automating widgets, from setup to advanced tuning techniques for busy teams."
og_image: "/images/widget-automation.png"
{faq_block}{howto_block}---
# How to Automate Widgets: A Best-Practice Guide

## Key Takeaways

Widget automation is a repeatable process that removes manual toil.

## What Is Widget Automation?

Widget automation refers to the use of scripts and templates to configure widgets without manual steps. See the [official widget docs](https://docs-example.test/widgets) for background.

## Comparison: Manual vs Automated

| Approach | Setup Time | Error Rate |
| --- | --- | --- |
| Manual | Slow | High |
| Automated | Fast | Low |

## Steps

1. Install the CLI.
2. Configure the manifest.
3. Run the automation job.

```bash
widget-cli run --config widgets.yaml
```
{faq_section}"""

_FAQ_FRONTMATTER = """faq:
  - question: "What is widget automation?"
    answer: "Widget automation is the practice of scripting repetitive widget configuration tasks."
  - question: "Why does it matter?"
    answer: "It reduces manual errors and frees engineering time for higher-value work."
"""

_HOWTO_FRONTMATTER = """howto_steps:
  - name: "Install the CLI"
    text: "Run the installer and confirm the widget-cli binary is on PATH."
  - name: "Configure the manifest"
    text: "Create a widgets.yaml file describing each automated widget."
"""

_FAQ_SECTION = """
## Frequently Asked Questions

### What is widget automation?

Widget automation is the practice of scripting repetitive widget configuration tasks.

### Why does it matter?

It reduces manual errors and frees engineering time for higher-value work.
"""


def _build_article(*, faq_section: bool, faq_frontmatter: bool, howto_frontmatter: bool) -> str:
    return _SELF_TEST_BASE.format(
        faq_block=_FAQ_FRONTMATTER if faq_frontmatter else "",
        howto_block=_HOWTO_FRONTMATTER if howto_frontmatter else "",
        faq_section=_FAQ_SECTION if faq_section else "",
    )


def self_test() -> None:
    # Regression for the deadlock this script once caused: agents stopped
    # emitting inline <script type="application/ld+json"> blocks (schema is
    # now generated by the site template from frontmatter), but the old
    # scoring hardcoded 20 points to that literal tag, capping every post at
    # 80/100 against blog-seo's 85-point gate. None of the fixtures below
    # contain an inline JSON-LD block; the max-achievable score must still
    # be 100, and a good post must still clear 85.
    assert '<script type="application/ld+json">' not in _SELF_TEST_BASE

    # A post with no FAQ/HowTo *sections* is not penalized for lacking
    # FAQ/HowTo frontmatter — it should still reach the full 100. The H1
    # itself reads "How to Automate...", so HowTo frontmatter is still
    # required for the full score even with no FAQ section.
    howto_only = evaluate_geo_citability(
        _build_article(faq_section=False, faq_frontmatter=False, howto_frontmatter=True)
    )
    assert howto_only["score"] == 100, howto_only

    # Full-featured post: FAQ section + FAQ frontmatter + HowTo frontmatter.
    # This is the maximum-achievable-score check.
    full = evaluate_geo_citability(
        _build_article(faq_section=True, faq_frontmatter=True, howto_frontmatter=True)
    )
    assert full["score"] == 100, full

    # A "good but not perfect" representative post must still clear the
    # blog-seo 85-point gate.
    assert full["score"] >= 85

    # FAQ section in prose WITHOUT structured FAQ frontmatter loses exactly
    # the 6 FAQ points — the discrimination the redesign is meant to keep.
    faq_prose_only = evaluate_geo_citability(
        _build_article(faq_section=True, faq_frontmatter=False, howto_frontmatter=True)
    )
    assert faq_prose_only["score"] == 94, faq_prose_only

    # A how-to-shaped post (H1 says "How to ...") WITHOUT structured HowTo
    # frontmatter loses exactly the 6 HowTo points.
    no_howto_data = evaluate_geo_citability(
        _build_article(faq_section=False, faq_frontmatter=False, howto_frontmatter=False)
    )
    assert no_howto_data["score"] == 94, no_howto_data

    # Missing core frontmatter fields costs 2 points each.
    missing_author = _build_article(faq_section=False, faq_frontmatter=False, howto_frontmatter=True)
    missing_author = missing_author.replace('author: "A. Writer"\n', "")
    result = evaluate_geo_citability(missing_author)
    assert result["score"] == 98, result

    print("[OK] ai_citation_score self-test passed")


def main() -> None:
    if "--self-test" in sys.argv[1:]:
        self_test()
        return

    if len(sys.argv) < 2:
        print("Usage: python3 ai_citation_score.py <path-to-markdown-file>")
        sys.exit(1)

    filepath = sys.argv[1]
    try:
        content = Path(filepath).read_text(encoding='utf-8')
    except Exception as e:
        print(f"Error reading file {filepath}: {e}")
        sys.exit(1)

    res = evaluate_geo_citability(content)
    print("=== AI CITATION & GEO READINESS REPORT ===")
    print(f"Overall GEO Score: {res['score']} / 100")
    print("\nBreakdown:")
    for k, v in res['breakdown'].items():
        print(f"  - {k.capitalize()}: {v}")


if __name__ == "__main__":
    main()
